### ISSUE TITLE
Feature Request: Add option to enable HTTP compression

### ISSUE THREAD

**Issue by hyshka** [lukaskubis/darkskylib#1]
From the DarkSky docs (https://darksky.net/dev/docs/response):

> The Forecast Data API supports HTTP compression. We heartily recommend using it, as it will make responses much smaller over the wire. To enable it, simply add an Accept-Encoding: gzip header to your request. (Most HTTP client libraries wrap this functionality for you, please consult your library’s documentation for details.)

The requests library can do this, but it seems that the option needs to be built into the library.

http://docs.python-requests.org/en/master/user/quickstart/#custom-headers

I could probably submit a PR for this but I don't have a timeline.

**Comment by lukaskubis** [comment]
I don't know how I missed that, I'm on it, thanx.
