### ISSUE TITLE
How to get historical data

### ISSUE THREAD

**Issue by HenriqueCSJ** [lukaskubis/darkskylib#10]
I couldn't find in the documentation an example on how to retrieve historical data for a time range.
Is this possible?

**Comment by lukaskubis** [comment]
@HenriqueCSJ The time machine request is the same as the usual forecast request with added `time` argument. I mentioned it [here](https://github.com/lukaskubis/darkskylib/blob/master/README.rst#api-calls) briefly, example in [official API docs](https://darksky.net/dev/docs#time-machine-request). I might add it explicitly though.
