### ISSUE TITLE
ImportError: cannot import name 'forecast' from 'darksky'

### ISSUE THREAD

**Issue by SomeGuyWithAPC** [lukaskubis/darkskylib#11]
I am having some issues running your example script. I receive the import error for forecast. I am using Idle 3.7 as well as python 3.7.

**Comment by LouisPi** [comment]
So you are running exactly this, 'from darksky import forecast' and it is not working. Did you install the library using pip?

**Comment by SomeGuyWithAPC** [comment]
Yes. I used both pip install darksky and darkskylib==0.3.91(I'm not sure of the exact number, but I know its the latest version)

**Comment by lukaskubis** [comment]
@SomeGuyWithAPC uninstall `darksky` package and force reinstall `darkskylib`

**Comment by SomeGuyWithAPC** [comment]
I am still receiving the same Import error. I made sure I ran the pip install --upgrade --force-reinstall darkskylib from an elevated command prompt.

**Comment by SomeGuyWithAPC** [comment]
Could it possibly be an issue with IDLE? I was able to run it from the shell, just not as a script.

**Comment by SomeGuyWithAPC** [comment]
Thank you for your help! After I force reinstalled the second time it work!
