### ISSUE TITLE
forecast method returned object is un-picklable

### ISSUE THREAD

**Issue by tadasmin** [lukaskubis/darkskylib#12]
The weather forecast data returned by forecast method, if written to disk as pickle files, later are unreadable due to :
RecursionError: maximum recursion depth exceeded while calling a Python object

To reproduce simply save forecast returned object as pickle and try to read it.

**Comment by lukaskubis** [comment]
Thanks for reporting this, I'll take a look soon.

**Comment by lukaskubis** [comment]
fixed in 08730160c7dd1b06b2c93ac4efab438725778bbf
