### ISSUE TITLE
How to fill missing historical data between two dates

### ISSUE THREAD

**Issue by evanhenry** [lukaskubis/darkskylib#15]
When there is no data for a specific date inside the queried range, it gives a "KeyError: 'temperature'. I would like to add some logic to avoid this error by fill the missing dates with NaN, and completing the query.

For now, I've been fetching the last date from the previous query, and running a new query starting from the time from the last query. This is pretty cumbersome and involves a lot of guess and check.

```
# grab only weather of interest
attributes = [u'temperature', u'humidity']
#initalize
times = []
data = {}
for attr in attributes:
    data[attr] = []

# Start date date 
date = datetime.datetime(2019, 3, 1, 0, 0)


for offset in range(1, 2): #range is in hours
    forecast = forecastio.load_forecast(api_key, lon, lat, time=date+datetime.timedelta(offset), units = 'ca' )
    h = forecast.hourly() # get forecase
    d = h.data # d = forecastio.models.ForecastioDataPoint
    for p in d:
        times.append(p.time)
        for i in attributes:
            try:
                data[i].append(p.d[i]) # try to append temp/humid data to timestamped list
            except KeyError as e:
                # FILL missing temp data from API with Nan until there is data 
                print(e.message) # printing error for now,

#Covernt to dataframe 
df1 = pd.DataFrame(data)
df2 = pd.DataFrame(times)

df = pd.concat([df1, df2], axis=1)
```

I expect the outputting dataframe of times to be the hours between the requested timedelta date-range, and the times df to be populated with the API's temperature data, or NaNs if there was not any data available.

**Comment by lukaskubis** [comment]
There is no `forecastio` module in this library, looks like you're using something else.

**Comment by evanhenry** [comment]
for offset in range(1, 2): #range is in hours
    forecast = forecastio.load_forecast(api_key, lon, lat, time=date+datetime.timedelta(offset), units = 'ca' )
