### ISSUE TITLE
Problem with alerts

### ISSUE THREAD

**Issue by elephantinedroid** [lukaskubis/darkskylib#16]
Hello - anyone still working on this?

I seem to be having trouble with alerts.

Based on the exact example language (as I am just fiddling around as I begin my project), I have:

`alerts = oneonta.alerts[0].title`

This then returns the following error:

```
Traceback (most recent call last):
  File "cloudweathertest.py", line 41, in <module>
    getWeather()
  File "cloudweathertest.py", line 37, in getWeather
    alerts = oneonta.alerts[0].title
  File "/usr/local/lib/python3.5/dist-packages/darksky/forecast.py", line 27, in              __getattr__
    return object.__getattribute__(self, key)
AttributeError: 'Forecast' object has no attribute 'alerts'
```

**Comment by lukaskubis** [comment]
@elephantinedroid did you check whether there actually are any alerts returned from the API?

**Comment by elephantinedroid** [comment]
Oh, jeez, I feel so dumb! Now I have, and I've got what I wanted working with try/except. Thanks for asking the obvious question and getting me back on track. :)
