### ISSUE TITLE
ModuleNotFoundError: No module named 'core' (again!)

### ISSUE THREAD

**Issue by eliasvitali** [lukaskubis/darkskylib#17]
I see this was a previous issue that was closed, but I was not able to resolve it with that thread so I'm hoping to get some help yet again.

This issue only began today, I went to run my program (which was fine a couple of days ago) and I got the following error:

```
  File "/home/evitali/Projects/analytics/src/analytics/utils/darkskyData.py", line 1, in <module>
    from darksky.api import DarkSky
  File "/home/evitali/Projects/venv/20190917/lib/python3.6/site-packages/darksky/__init__.py", line 1, in <module>
    from core import *
ModuleNotFoundError: No module named 'core'
```
Trying to simply `import darksky` on its own yields the same thing:

```
Python 3.6.8 (default, Oct  7 2019, 12:59:55) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import darksky
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/evitali/Projects/venv/20190917/lib/python3.6/site-packages/darksky/__init__.py", line 1, in <module>
    from core import *
ModuleNotFoundError: No module named 'core'
```
Here are the contents of `/home/evitali/Projects/venv/20190917/lib/python3.6/site-packages/darksky/`:

```
├── api.py
├── base.py
├── core.py
├── data.py
├── exceptions.py
├── forecast.py
├── __init__.py
├── __pycache__
│   ├── api.cpython-36.pyc
│   ├── base.cpython-36.pyc
│   ├── core.cpython-36.pyc
│   ├── data.cpython-36.pyc
│   ├── exceptions.cpython-36.pyc
│   ├── forecast.cpython-36.pyc
│   ├── __init__.cpython-36.pyc
│   ├── request_manager.cpython-36.pyc
│   └── utils.cpython-36.pyc
├── request_manager.py
├── types
│   ├── __init__.py
│   ├── languages.py
│   ├── __pycache__
│   │   ├── __init__.cpython-36.pyc
│   │   ├── languages.cpython-36.pyc
│   │   ├── units.cpython-36.pyc
│   │   └── weather.cpython-36.pyc
│   ├── units.py
│   └── weather.py
└── utils.py
```
where you can see `core.py` is clearly in the same top-level directory as `__init__.py`

**Things I have tried**

1. Upgrading `darksky` and `darkskylib`

I was already on the latest version.

2. Reading and implementing the solution discussed [here](https://github.com/lukaskubis/darkskylib/issues/4)

Specifically, changing the line in `__init__.py` to:
* `from .core import *`
* `from darksky.core import *`

Neither of which solved the problem and both resulted this Traceback:

```
Python 3.6.8 (default, Oct  7 2019, 12:59:55) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import darksky
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/evitali/Projects/venv/20190917/lib/python3.6/site-packages/darksky/__init__.py", line 1, in <module>
    from darksky.core import *
  File "/home/evitali/Projects/venv/20190917/lib/python3.6/site-packages/darksky/core.py", line 8, in <module>
    import mapq
  File "/home/evitali/Projects/venv/20190917/lib/python3.6/site-packages/mapq/__init__.py", line 1, in <module>
    from .core import key, address, batch, geocode, latlng, reverse
  File "/home/evitali/Projects/venv/20190917/lib/python3.6/site-packages/mapq/core.py", line 5, in <module>
    from .geo import Geo
  File "/home/evitali/Projects/venv/20190917/lib/python3.6/site-packages/mapq/geo.py", line 8, in <module>
    from urllib import unquote
ImportError: cannot import name 'unquote'
```
At this point I am at a loss. Any insight is appreciated

Edit: Looking at your repository, it seems that `core.py` is not even part of it anymore? But the last commit was almost 2 years ago and this problem began for me today and was talked about last year in Issue #4

**Comment by lukaskubis** [comment]
@eliasvitali if you take a look at the source code of this library, you'll see there is no `core.py` module. This is a conflict between `darksky` and `darkskylib`. Uninstall `darksky` and force reinstall `darkskylib`.

```
pip uninstall darksky && pip install darkskylib --upgrade --no-cache- --force-reinstall
```
As discussed [here](https://github.com/lukaskubis/darkskylib/issues/4#issuecomment-376594794)
