### ISSUE TITLE
v0.3.6 throws TypeError: '_GeneratorContextManager' object is not subscriptable

### ISSUE THREAD

**Issue by Brawl345** [lukaskubis/darkskylib#2]
Hello,
v0.3.6 doesn't seem to work anymore - example code:
```
from darksky import forecast
key='APIKEY'
boston = forecast(key, 42.3601, -71.0589)
boston['currently']
```
and then I get this traceback:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: '_GeneratorContextManager' object is not subscriptable
```
Downgraded to v0.3.5 and it worked again.

**Comment by lukaskubis** [comment]
That's interesting. Which version of python? I'll take a look asap, for now keep using v0.3.6. 
Cheers!

**Comment by Brawl345** [comment]
v0.3.5 you mean :P I'm using Python 3.6.1 on Windows 10 x64

**Comment by lukaskubis** [comment]
AAA yes I see now, this is a change in functionality, whereby the `forecast` function, instead of returning `Forecast` object, now acts just as a context manager, yielding the `Forercast` inside a `with` statement.

try one of these: (I'm unable to do so at this time):

```python
from darksky import forecast
key='APIKEY'
with forecast(key, 42.3601, -71.0589) as boston:
    boston['currently']
```

```python
from darksky import forecast
key='APIKEY'
boston = Forecast(key, 42.3601, -71.0589)
boston['currently']
```

I'll keep this issue open until I do something about this.
Thanks for letting me know.

**Comment by pshdev** [comment]
I have the same error, and do not have the previous version to downgrade too. 

Both of those work-arounds do not work for me.

**Comment by Brawl345** [comment]
Just use
```
pip uninstall darkskylib
pip install darkskylib==0.3.5
```
to install the old version.

**Comment by lukaskubis** [comment]
I'll revert this nonsense back to what it was during the weekend and update the whole thing. I don't even remember what was my original intention behind this.

**Comment by mlasevich** [comment]
FWIW, I think you can avoid using a wrapper and maker it be able to be used in context by adding  `__enter__()`/`__exit__()` methods to the `Forecast()` object. This will cut down on confusion and work in either case

**Comment by lukaskubis** [comment]
I know, that's how it was before, reverting.
