### ISSUE TITLE
Apple has purchased Dark Sky and is shutting down the API.

### ISSUE THREAD

**Issue by tinohager** [lukaskubis/darkskylib#24]
Apple has purchased Dark Sky and is shutting down the API.
The API will continue to function through the end of 2021.
[More Informations](https://blog.darksky.net/)

**Comment by seaniedan** [comment]
I put this on my repo: 
## ALERT: [Dark Sky, the provider on which this repo relies, will no longer accept new signups. The API will continue to function through the end of 2021.](https://blog.darksky.net/dark-sky-has-a-new-home)
