### ISSUE TITLE
No way to add timeout to request

### ISSUE THREAD

**Issue by mlasevich** [lukaskubis/darkskylib#3]
I run into this code locking up if API endpoint are not available. `requests.get()` supports timeout parameter, but it is not used and I see no way to set it.

**Comment by lukaskubis** [comment]
I'm on it

**Comment by lukaskubis** [comment]
@mlasevich done, update to [v0.3.9](https://github.com/lukaskubis/darkskylib/releases/tag/v0.3.9)

**Comment by mlasevich** [comment]
Thanks for incredibly quick response and turnaround :-)  

However, unfortunately there is a `,` missing in https://github.com/lukaskubis/darkskylib/blob/master/darksky/__init__.py#L6 between `timeout=None` and `**queries`, making the whole thing fail to load :-(

**Comment by lukaskubis** [comment]
yeah, already on it, just figuring out versioning... but you can clone the repo and use code from that, that's already fixed

**Comment by lukaskubis** [comment]
@mlasevich [v0.3.91](https://pypi.org/project/darkskylib/0.3.91/) and let's act like nothing happened 😶

**Comment by mlasevich** [comment]
LOL. I did test it by manually adding the `,` in local install and timeout functionality worked great. Will retest with the new version, but can't imagine it would be any different :-)

Thanks again!

(Update, 0.3.91 worked great)
