### ISSUE TITLE
Possibility to pass more parameters

### ISSUE THREAD

**Issue by lsteffenel** [lukaskubis/darkskylib#7]
Hello, thank you for the library, it's a nice work :) 

I'm writing you because I would like to pass additional parameters like "&units=si" to directly get values in Celsius and m/s, or to change the language for the summary. 

I could not find how to do this through your library, perhaps I'm just too dumb... If not, can you add this possibilities in a future update?

Thank you!

**Comment by lukaskubis** [comment]
Hi, all the additional parameters as documented in the api should be supported by default, you just add them as keyword arguments after the first three mandatory ones (`key`, `latitude`, `longitude`). 

example:

```python
f = forecast(api_key, latitude, longitude, units='si', lang='en')
```

**Comment by lsteffenel** [comment]
Cool, thank you for the quick reply 👍
